name: CivilizationCraftStatisticsTracker
main: statistics_tracker.CivilizationCraftStatistics
version: 1.0
api-version: 1.16
commands:
   civStatsAdmin:
      description: List and use CCST admin commands.
      usage: |
         
         /<command> - Lists and describes all admin commands.
         /<command> [command] - Executes specific command.
      permission: CivilizationCraftStatisticsTracker.administrator
      permission-message: "Unknown command. Type \"/help\" for help."
permissions:
   CivilizationCraftStatisticsTracker.administrator:
      description: Allows use of civStatsAdmin commands.
      default: op